version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./packages/web/.env
    environment:
      NODE_ENV: development

  ai:
    build:
      context: .
      dockerfile: packages/ai/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  default:
    driver: bridge
