name: Deploy to Digital Ocean Kubernetes

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files in the web directory
        run: ls -alh ./web

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: filipvdb321/budget-ai:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save Digital Ocean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-1-vandenit-ams3-dev

      - name: Deploy config to Kubernetes
        run: |
          kubectl apply -f ./kube/config/dev

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kube/dev

      - name: Verify deployment
        run: kubectl rollout status deployment/budget-ai-app -n dev
